### ISSUE TITLE
Server.GetAllAsync() not working

### ISSUE THREAD

**Issue by ljchuello** [lk-code/hetzner-cloud-api-net#24]
Hello..

When trying to perform a Server.GetAsync(serverId) or a GetAllAsync() I receive an error of the type **"Message = "Object reference not set to an instance of an object.""** It seems to me that something is happening with the token.

This is the code I am using. (I have deleted the token for security, but at the time of testing it was activated)
![Captura](https://user-images.githubusercontent.com/5316348/204893465-dbdf7eb0-ca14-4211-a71a-36f9500048f7.PNG)

And then I get this error.
![Sin título](https://user-images.githubusercontent.com/5316348/204893792-52046fd2-7138-4918-8458-5ab165942e03.png)

I will appreciate your help. Thanks.

**Comment by lk-code** [comment]
Hi,

Which version do you have installed?

I just created a new CLI app project and then installed the latest version (2.0.8) via NuGet:

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1656571/205098349-5ef8d658-d8bd-47c5-852a-05da3e531c19.png">

**Comment by ljchuello** [comment]
Hello,

This is what seems most strange to me, I also have the latest version of hetznercloudapi (2.0.8) via NuGet.

![image](https://user-images.githubusercontent.com/5316348/205127784-8fa92cff-fa67-48a9-a7db-6c6c3064499d.png)

Is it possible that I can pass you my API KEY and you can try it for me?

![image](https://user-images.githubusercontent.com/5316348/205128088-c631aed2-769c-4740-b12b-9a14ebbbbfa9.png)

I'm using NET Core 6, maybe it's a problem with the version of NET Core?

**Comment by lk-code** [comment]
Hi,

write an email to lk-code@outlook.de :)

**Comment by lk-code** [comment]
RESPONSE: The server does not have an assigned IPv6, so the mapping failed. The bug has been fixed and is available in version 2.0.10.
