### ISSUE TITLE
Missing CreateServer

### ISSUE THREAD

**Issue by GarethWright** [lk-code/hetzner-cloud-api-net#3]
Create Server action isn't present. (Unless I'm going blind)

**Comment by lk-code** [comment]
This point is currently in work and will be coming soon ;)

**Comment by GarethWright** [comment]
I see this has been added. Your issue with passing an image is that you need to pass the image id not the description.

This will then also work for snapshots.

**Comment by GarethWright** [comment]
Looks like you already changed that in latest code.....working!
